# .streamlit/secrets.toml

# OpenAI API Key: ChatGPT 등의 모델 호출에 사용
OPENAI_API_KEY = "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"

# Plant.ID API Key: 식물 이미지 진단 및 식별에 사용
PLANTID_API_KEY = "ibzgk86dMawEKs4RDIlWxIonfwlzxeEriB6F5aaYKBmQ9WGRvR"

# 농사로 API Key: 농업 관련 재배 정보 및 기타 데이터 조회에 사용
NONGSARO_API_KEY = "20250813CU0ELON3Z1PFTF48ZTWMQQ"

# 스마트팜 코리아 Open API Key: 스마트팜 장치 데이터 조회에 사용
SMARTFARM_KOREA_API_KEY = "a68c535abf4049cc933ead5e8ab50a7b"

# AI Hub API Key: AI Hub의 스마트팜, 병해충, 작물 데이터셋 관련 API에 사용
AIHUB_API_KEY = "86B97488-77AE-4D55-95F8-BB0A61DC47BA"

# 기상청 (KMA) API Key: 기상청 단기/초단기 예보 및 실황 조회에 사용
KMA_API_KEY = "rVPFCq7gAPU8aaf9zdyijb4VngBMeSGAE5l7XVprXp%2B7ObhpA55kReLoE91ilZfO5GorH5b7yksRF9R8m7vVNA%3D%3D"

# 농촌진흥청(RDA) 농업기상 기본 관측데이터 조회 API Key
# 이 키 값이 KMA_API_KEY와 다르다면, 해당 서비스에서 발급받은 고유한 키로 변경해주세요.
# 현재 KMA_API_KEY와 동일한 값이므로, 필요에 따라 확인 및 수정이 필요합니다.
RDA_WEATHER_API_KEY = "rVPFCq7gAPU8aaf9zdyijb4VngBMeSGAE5l7XVprXp%2B7ObhpA55kReLoE91ilZfO5GorH5b7yksRF9R8m7vVNA%3D%3D"

# 농촌진흥청(RDA) 농업기상 상세 관측데이터 조회 API Key
# 이 키는 KMA API Key와 다른 키이므로 별도 관리합니다.
RDAD_WEATHER_API_KEY = "grmT9mnnmAl6Mwvt0SxW%2Fxl544FREIVwiHG8VPars%2Ban14ioHJtHkH8Sb%2B54blxm%2Fn6UN9NKrF9Tccf4nXXYOg%3D%3D"